version = 1

exclude_patterns = [  
  "scripts/**",  
  "**/node_modules/",  
  "examples/**"
  "docs"
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react"
  ]
  style_guide = "standard"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"