version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react"
  ]
  style_guide = "standard"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"