name: 'Install'
description: 'Sets up Bun and runs install'

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org'

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "nsk9195@gmail.com"
        git config --global user.name "Shubham Kaushal"

    - name: Install dependencies
      shell: bash
      run: bun install
