name: Check Size Limit
on: [pull_request]
jobs:
  check-size-limit:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build React Package
        run: bun run build:react

      - name: Build Svelte Package
        run: bun run build:svelte

      - name: Perform Size limit Checkup
        uses: andresz1/size-limit-action@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: ./
          package_manager: bun
