name: Size Limit
on:
  pull_request:
  push:

concurrency:
  group: ci-size-limit=${{github.ref}}-1
  cancel-in-progress: true

env:
  SL_BASELINE_REPORT_FOLDER: size-limit-report
  REPORT_OUTPUT_DIR: ./size-report

jobs:
  generate-size-limit-react:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Generate Size Report
        id: generate_report
        run: node ./scripts/ci/generate-size-report.mjs
        env:
          REPORT_OUTPUT_DIR: ./size-report

      - name: Upload Pull Request Specific Reports
        if: github.event.number
        uses: actions/upload-artifact@v3
        with:
          name: size-report-artifact-pr-${{ github.event.number }}
          branch: ${{ github.event.pull_request.base.ref }}
          path: ./size-report

  create-or-update-size-report-comment:
    runs-on: ubuntu-latest
    if: github.event.number
    needs: generate-size-limit-react

    steps:
      - name: Download Baseline Report Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: size-limit.yml
          branch: ${{ github.event.pull_request.base.ref }}
          path: ./__compare

      - name: Download Pull Request Report Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          name: size-report-artifact-pr-${{ github.event.number }}
          path: ${{ env.REPORT_OUTPUT_DIR }}

      - name: Generate Size Report Comparison Table
        id: compare
        run: node ./scripts/ci/get-mark-down-table.mjs
        env:
          COMPARING_REPORT_FILE_PATH: ${{ env.REPORT_OUTPUT_DIR }}/size-report.json
          BASELINE_REPORT_FILE_PATH: ./__compare/size-report.json

      - name: Find Size Report Comment
        uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Size Report

      - name: Create Size Report Comment
        if: steps.find_comment.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Size Report
            ---
            Created Comment

      - name: Update Size Report Comment
        if: steps.find_comment.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          body: |
            ### Size Report
            ---
            This comment has been updated!
